### PR TITLE
DOC: add preview of AmpForm-DPD model deserialization

### PR DESCRIPTION
**Pull request by redeboer**
Added a page for Lc to pKpi that illustrates https://github.com/ComPWA/ampform-dpd/pull/132 (preview).

> [!WARNING]
> The model validation does not work yet, for now the page just illustrates the symbolic rendering of the deserialized model. Keep an eye on https://github.com/ComPWA/ampform-dpd/issues/133 for upcoming fixes.

### CODE REVIEW

**Comment by redeboer** [comment]
@mmikhasenko the page has been converted from a Jupyter notebook with MyST syntax and is not yet optimal for Quarto. On the road today, hope to get back to that later today. The PR should be merged before tomorrow afternoon.

**Comment by mmikhasenko** [comment]
Looks great, @redeboer.
I could not spot any problems right away: maybe it matches once the `nan` is solved.

**Comment by mmikhasenko** [comment]
Combination of `s` (GeV^2), and masses (GeV) does not look right, if the order of the argument changes (production vs decay of resonance)

image

**Comment by mmikhasenko** [comment]
p^{2L} is missing.

image

my form-factor includes z^{2l} in the numerator, that is why there is no p^{2l+1} in [julia code](https://github.com/mmikhasenko/HadronicLineshapes.jl/blob/main/src/shapes.jl#L18-L27). Just 2p/sqrt{s}

**Comment by redeboer** [comment]
I'm doubting btw between merging this PR for now to get at least the preview up or addressing the issues first. Don't think I can handle that quickly because it might require a new prerelease of AmpForm-DPD.

**Comment by redeboer** [comment]
> Combination of `s` (GeV^2), and masses (GeV) does not look right, if the order of the argument changes (production vs decay of resonance)

Good point, though more of a design problem + latex rendering problem? You would just have to square the mass. But yeah if there is some argument swapping going on programmatically this is tricky...

**Comment by redeboer** [comment]
@mmikhasenko seeing that CI takes some time, I would prefer to merge this one (and #45?) asap. Remaining issues will be addressed through https://github.com/ComPWA/ampform-dpd/issues/133 and a follow-up PR here.

**Pull request merged**
