### PR TITLE
Extend validation

### LINKED ISSUE #36: Add arguments for functions
Our functions used for lineshapes, should indicared mass squared variable that in depends on.

The description,
```
    {
      "name": "D1232_BW",
      "l": 1,
      "mb": 0.13957018,
      "type": "BreitWigner",
      "d": 1.5,
      "mass": 1.232,
      "ma": 0.938272046,
      "width": 0.117
    },
```
would need to mention `x: m_ppi_squared`, and define `m_ppi_squared` below.

In HS3, all distributions and functions have their variables listed, e.g. `Gauss(x|mean,sigma)` describes all three variables.

```
{
  "distributions": [
    {
      "mean": "mean",
      "name": "gauss",
      "sigma": "sigma",
      "type": "gaussian_dist",
      "x": "x"
    }
  ],
  "domains": [
    {
      "axes": [
        { "max": 10.0, "min": -10.0, "name": "mean" },
        { "max": 10.0, "min": 0.1, "name": "sigma" },
        { "max": 10.0, "min": -10.0, "name": "x" }
      ],
      "name": "default_domain",
      "type": "product_domain"
    }
  ],
  "metadata": {
    "hs3_version": "0.2",
    "packages": [{ "name": "ROOT", "version": "6.33.01" }]
  },
  "parameter_points": [
    {
      "name": "default_values",
      "parameters": [
        { "name": "x", "value": 0.0 },
        { "name": "mean", "value": 1.0 },
        { "name": "sigma", "value": 1.0 }
      ]
    }
  ]
}
```

### Preparation
- [x] compute lineshape validation checks, (sigma_i, lineshape, value) for all lineshapes (just running the model in julia session)
- [x] report here

### Incorporate it in JSON:
- [x] Introduce a few new variables, `m12sq`, `m23sq`, and `m31sq` in "domains"(?).
- [x] for every lineshape add a field "variables" with an appropriate value, e.g. "variables"=["m12sq"].
- [x] add validations points, "validation_point_X", which indicate the value of the variables.

### LINKED ISSUE #44: Add checksums for dynamics functions
https://github.com/ComPWA/ampform-dpd/pull/132 implements deserialization for `Lc2ppiK.json`. I can't get the model to match yet, so it would be good to have an intermediate check on the dynamics functions.

@mmikhasenko could you add some checksums for the validation point in `Lb2pKg.json` and `Lc2ppiK.json`?

### PR DESCRIPTION
**Pull request by IlyaSegal**
Closes #44 and closes #36 

Implemented validation checks for different lineshapes.

### CODE REVIEW

**Comment by mmikhasenko** [comment]
@IlyaSegal a few suggestions:
 - rename `name` -> `point` in the validation section. It makes more sense, I think. I've done it already in [the `X2pipipi_compass` file](https://github.com/RUB-EP1/amplitude-serialization/blob/main/models/x2pipipi-compass-1391643.json#L1137).
  - not all BWs in `lc2ppiK` are functions of `m_12^2`, only `Delta`s. The `K(..)` are functions of  `m_23^2`, while `Lambda`s are functions of `m_31^2`

otherwise, looks good to me

**Comment by mmikhasenko** [comment]
@IlyaSegal the conflicts should be straightforward, shell we merge it today?

**Review by mmikhasenko — APPROVED** [review]
I thought that one can introduce "x" mandatory in schema, but not true for BlattWeisskopf, nor for generic. So, it's cannot be mandatory 

Once the x2pipipi passes lineshape checks, I sign off,
Looks good to me, thanks a lot @IlyaSegal

**Comment by IlyaSegal** [comment]
@mmikhasenko validation for X to 3pi is there.
The only thing that is left is to implement validation of lineshapes to Python notebook.
That's why the test fails for now. @redeboer, can you help with this?

**Pull request merged**
